# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('c0', 'Accepted'), ('c1', 'In progress'), ('c2', 'Shipped'), ('c3', 'Delivered'), ('c4', 'Completed')], default='c0', max_length=2),
        ),
    ]
