# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0005_productattribute_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, upload_to='product_photo'),
        ),
    ]
