# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='photo',
            field=models.FileField(blank=True, upload_to='bikeshop/media/catalog_photo'),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='photo',
            field=models.FileField(blank=True, upload_to='bikeshop/media/category_photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, upload_to='bikeshop/media/product_photo'),
        ),
    ]
