# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0012_auto_20160325_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='bikeshop.Product'),
        ),
    ]
